### ISSUE TITLE
Update buck branch in r8 to latest.

### ISSUE THREAD

**Issue by raviagarwal7** [facebookexperimental/r8#4]
r8 buck branch hasn't been updated since April, 2019.

I have pushed two branches https://github.com/raviagarwal7/r8/tree/ravi/buck-rebased which rebases current buck branch to latest master and another https://github.com/raviagarwal7/r8/tree/ravi/buck-merged which merges master into buck.

What workflow we would want to incorporate?

I would suggest we go with the rebase to keep the history and change sets clean:
- Tag current `buck` branch reference for future 
- Update `buck` branch to latest `ravi/buck-rebased` branch
- Squash similar commits (code changes into one and non-code changes into one)
- Update `buck` in fb r8

On a side note, is it possible to merge the bucketing changes into r8 upstream?

Please let me know your thoughts. @justinjhendrick

**Comment by justinjhendrick** [comment]
Awesome, thanks for doing this! I have one request though, can we update to the latest release branch of r8 instead of master? Should be more stable and less risky.

> What workflow we would want to incorporate?

I don't have a strong preference. We can go with rebases if you prefer.

> On a side note, is it possible to merge the bucketing changes into r8 upstream?

I'm not sure. I was under the impression they were put here precisely because they couldn't be merged upstream, but I never actually confirmed that.

**Comment by raviagarwal7** [comment]
Sounds good. I will update it to the release branch instead.

**Comment by raviagarwal7** [comment]
I have pushed a branch https://github.com/raviagarwal7/r8/tree/ravi/buck-rebased which is rebased on top of [agp-3.6.1](https://r8.googlesource.com/r8/+/refs/tags/agp-3.6.1). agp-4.x is still in beta.

Could you update the `buck` branch to point to it and also tag the existing branch ref.

I will create a PR on buck side to update d8 jar as well

**Comment by justinjhendrick** [comment]
> Could you update the buck branch to point to it and also tag the existing branch ref.

Yes, I'll do that today.

> I will create a PR on buck side to update d8 jar as well

Wonderful, thank you.

**Comment by justinjhendrick** [comment]
Sorry for the delays. I've been trying to make the switch today but I've been running into issues. To be honest, I'm less familiar with git. I mostly use hg.

When I tried to rebase https://github.com/raviagarwal7/r8/tree/ravi/buck-rebased into `buck` I got merge conflicts, which I wasn't expecting. I thought you took care of all the merge conflicts in https://github.com/raviagarwal7/r8/tree/ravi/buck-rebased?

**Comment by raviagarwal7** [comment]
you don't need to rebase the `ravi/buck-rebased` branch since it is already rebased.

you can use the following commands to update.

```
// checkout remote buck commit
git checkout origin/buck
// tag it 
git tag buck_0
// push the buck_0 tag
git push origin buck_0

// checkout the buck branch
git checkout buck
// force set it's head to the rebased 
git reset --hard ravi/buck-rebased 

// force push to remote (it is required since it is not fast forward)
git push origin buck
```

let me know if you encounter any issues

**Comment by justinjhendrick** [comment]
Done. Let me know if it looks right to you. Thanks for the help with the git commands :)

**Comment by raviagarwal7** [comment]
thanks, @justinjhendrick this looks good. I will close the issue.
